// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grlticdfbtugciydmrqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdybHRpY2RmYnR1Z2NpeWRtcnFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTk1NzQsImV4cCI6MjA1OTI3NTU3NH0.VMD7yL2faUaM5Ubg09ncAQuqbTuuMAL2BmjnpL39zIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);